title: ROSH@N KUMAR
logo: "/profile-image.png?raw=true"
description: >
 Java Microservice Developer | Site Reliability Engineer
  <br><br>
  <a href="mailto:roshankr1310@gmail.com">roshankr1310@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/roshan-kr-1310//">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/roshankumardotcom">Gihub</a> 
theme: jekyll-theme-minimal
